# import unittest
#
# from project.battle_field import BattleField
# from project.player.beginner import Beginner
#
#
# class BattleFieldTests(unittest.TestCase):
#     def test_fight_exception(self):
#         attacker = Beginner("Pesho")
#         enemy = Beginner("Gosho")
#         attacker.health -= 51
#         BattleField.fight(attacker, enemy)